# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(verbose_name='date posted'),
        ),
    ]
